services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.1
    platform: linux/amd64
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181 # порт слушания брокеров
      ZOOKEEPER_TICK_TIME: 2000 
    ports:
      - "2181:2181" #хост из контейнера на порт

  kafka:
    image: confluentinc/cp-kafka:7.4.1
    platform: linux/amd64
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181" # адрес Zookeeper внутри Docker-сети
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092 # Kafka сообщает адрес клиентам для клиентов
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092 # интерфейс, на котором брокер слушает подключения внутри контейнера.
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 # хранит информацию "какие сообщения уже прочитаны" на одном брокере.
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1 # хранит состояние транзакций (как в БД) на одном брокере.
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1 # подтверждение записи, если брокер ее сохранил

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: etl_user
      POSTGRES_PASSWORD: etl_pass
      POSTGRES_DB: etl_db 
    ports:
      - "5432:5432" # порт Postgres на хост
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: 
